version: '3.8'

services:
  db:
    image: postgres:16
    container_name: csstorage_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cs_storage
    ports:
      - "4321:4321"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: csstorage_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__Default=Host=db;Database=csstorage;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./CsStorage.WebUI/cs_storage
      dockerfile: Dockerfile
    container_name: csstorage_frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  pgdata:
