name: Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Set working directory
        working-directory: backend/cs-storage-core  

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Upload to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cs-storage
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
